# Generated by Django 5.1.6 on 2026-01-23 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GITHUB', 'GitHub Agent'), ('AUDIO', 'Audio Agent')], max_length=20)),
                ('agent_type', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/audio/')),
                ('output_data', models.TextField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=18, default=0.001, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
