# Generated by Django 5.1.6 on 2026-01-25 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Transaction', 'verbose_name_plural': 'Analysis Transactions'},
        ),
        migrations.AlterField(
            model_name='analysistransaction',
            name='category',
            field=models.CharField(choices=[('GITHUB', 'GitHub Agent'), ('AUDIO', 'Audio Agent'), ('COMPETESCAN', 'CompeteScan AI'), ('SCRAPER', 'Web Scraper')], max_length=20),
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('profile', models.CharField(choices=[('executive_brief', 'Executive Brief'), ('technical_deep_dive', 'Technical Deep Dive'), ('developer_response', 'Developer Response'), ('strategy_risk', 'Strategy + Risk')], max_length=50)),
                ('model_a', models.CharField(max_length=50)),
                ('model_b', models.CharField(max_length=50)),
                ('response_a', models.TextField()),
                ('response_b', models.TextField()),
                ('winner', models.CharField(choices=[('A', 'Response A'), ('B', 'Response B')], max_length=1)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=18, default=0.0001, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Evaluation',
                'verbose_name_plural': 'Model Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
