# Generated by Django 5.1.6 on 2026-01-23 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('STATIC', 'Static QR'), ('DYNAMIC', 'Dynamic QR')], default='DYNAMIC', max_length=10)),
                ('amount_mon', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('receiver_wallet', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_wallet', models.CharField(max_length=42)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('chain_id', models.CharField(default='10143', max_length=10)),
                ('amount_mon', models.DecimalField(decimal_places=8, max_digits=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.paymentrequest')),
            ],
        ),
    ]
