"""
Django settings for web3_ai project.
=====================================
Environment Variables (.env) se values load hoti hain
Render Deployment ke liye Ready hai ye file!
=====================================

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===========================================
# SECURITY SETTINGS - .env SE LOAD HOTI HAIN
# ===========================================

# SECRET_KEY: .env file se load hogi, fallback hai agar .env nahi mili
SECRET_KEY = config('SECRET_KEY', default='django-insecure-w@tf=&^-bu$@*%2dra1nie2#cm%2s1fy-lg)01xs!jf48wg%$8')

# DEBUG: Production mein False hona chahiye (.env mein set karo)
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS: Comma-separated domains (.env mein set karo)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wallet', 
    'agents',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise Middleware - Production mein static files serve karne ke liye (RENDER KE LIYE MUST!)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web3_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web3_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 3. Set Custom User Model
AUTH_USER_MODEL = 'wallet.WalletUser'

# ===========================================
# STATIC FILES CONFIGURATION (Render Ready!)
# ===========================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Production ke liye STATIC_ROOT (collectstatic command use karti hai)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise Storage - Compressed aur cached static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ===========================================
# LOGIN/LOGOUT REDIRECTS
# ===========================================
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ===========================================
# AI SERVICES API KEYS (.env SE LOAD HOTI HAIN)
# ===========================================
# Google Gemini API Key - AI features ke liye
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')

# ElevenLabs API Key - Text-to-Speech ke liye
ELEVENLABS_API_KEY = config('ELEVENLABS_API_KEY', default='')

# ===========================================
# DATABASE: Default SQLite use ho raha hai
# Future mein PostgreSQL use karna ho to uncomment karo:
# ===========================================
# import dj_database_url
# DATABASES['default'] = dj_database_url.config(
#     default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'
# )
